# Where should we write the GIF?
Output add.gif

Require webman
Require fish

Set Shell fish

# Set up a 1200x600 terminal with 46px font.
Set FontFamily "GeistMono Nerd Font"
Set FontSize 18
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "webman add bun rg exa tokei helix glow"

# Pause for dramatic effect...
Sleep 50ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 15s