# Where should we write the GIF?
Output webman.gif

Require webman
Require fish

Set Shell fish

# Set up a 1200x600 terminal with 46px font.
Set FontFamily "GeistMono Nerd Font"
Set FontSize 20
Set Width 1200
Set Height 1200

# Type a command in the terminal.
Type "webman"

# Pause for dramatic effect...
Sleep 50ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s